apiVersion: v1
data:
  quota: |
    allocated_budget: '100.0'
    allocated_cpus: '20'
    allocated_memory_gb: '50'
    allocated_storage_gb: '1000'
    allocated_vms: '10'
    used_budget: '0.0'
    used_cpus: '0'
    used_memory_gb: '0'
    used_storage_gb: '0'
    used_vms: '0'
kind: ConfigMap
metadata:
  name: redhat-quota
