plan_name: Platinum
provisioned_storage: 20
plan_description: Platinum Plan
plan_long_description: This is the Platinum Plan - 7 Data Nodes, 1 Job Tracker
plan_display_name: This is the Platinum Plan - 7 Data Nodes, 1 Job Tracker
plan_cost: 9.99
option_0_cores_per_socket: 2
option_0_number_of_vms: 8
option_0_vm_memory: 4
option_0_number_of_sockets: 1
