- name: Fetch the CFME credentials
  k8s_v1_secret:
    namespace: "{{ namespace }}"
    name: cloudforms
    state: present
    force: false
  register: cloudforms_cred

- name: Create the error file
  lineinfile: 
    line: "Missing a secret called cloudforms in project {{ namespace }}"
    path: /dev/termination-log
    unsafe_writes: true
  when: cloudforms_cred is not defined

- fail: msg="Stopping playbook missing secret cloudforms in project {{ namespace }}"
  when: cloudforms_cred is not defined
